apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: node01
  name: node01
spec:
  containers:
  - image: nginx
    name: node01
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
